Failed to download Mistral-7B-v0.1 (Base). Error: Fetching 14 files: 0%| | 0/14 [00:00<?, ?it/s] Fetching 14 files: 0%| | 0/14 [00:00<?, ?it/s] Traceback (most recent call last): File "C:\Users\AliDesktop\AppData\Roaming\Python\Python312\site-packages\huggingface_hub\utils_http.py", line 409, in hf_raise_for_status response.raise_for_status() File "C:\Users\AliDesktop\AppData\Roaming\Python\Python312\site-packages\requests\models.py", line 1026, in raise_for_status raise HTTPError(http_error_msg, response=self) requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://huggingface.co/mistralai/Mistral-7B-v0.1/resolve/27d67f1b5f57dc0953326b2601d68371d40ea8da/.gitattributes

The above exception was the direct cause of the following exception:

Traceback (most recent call last): File "<frozen runpy>", line 198, in _run_module_as_main File "<frozen runpy>", line 88, in _run_code File "C:\Users\AliDesktop\AppData\Roaming\Python\Python312\site-packages\huggingface_hub\commands\huggingface_cli.py", line 65, in <module> main() File "C:\Users\AliDesktop\AppData\Roaming\Python\Python312\site-packages\huggingface_hub\commands\huggingface_cli.py", line 61, in main service.run() File "C:\Users\AliDesktop\AppData\Roaming\Python\Python312\site-packages\huggingface_hub\commands\download.py", line 157, in run print(self._download()) # Print path to downloaded files ^^^^^^^^^^^^^^^^ File "C:\Users\AliDesktop\AppData\Roaming\Python\Python312\site-packages\huggingface_hub\commands\download.py", line 191, in _download return snapshot_download( ^^^^^^^^^^^^^^^^^^ File "C:\Users\AliDesktop\AppData\Roaming\Python\Python312\site-packages\huggingface_hub\utils_validators.py", line 114, in _inner_fn return fn(*args, **kwargs) ^^^^^^^^^^^^^^^^^^^ File "C:\Users\AliDesktop\AppData\Roaming\Python\Python312\site-packages\huggingface_hub_snapshot_download.py", line 332, in snapshot_download thread_map( File "C:\Users\AliDesktop\AppData\Roaming\Python\Python312\site-packages\tqdm\contrib\concurrent.py", line 69, in thread_map return _executor_map(ThreadPoolExecutor, fn, *iterables, **tqdm_kwargs) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "C:\Users\AliDesktop\AppData\Roaming\Python\Python312\site-packages\tqdm\contrib\concurrent.py", line 51, in _executor_map return list(tqdm_class(ex.map(fn, *iterables, chunksize=chunksize), **kwargs)) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "C:\Users\AliDesktop\AppData\Roaming\Python\Python312\site-packages\tqdm\std.py", line 1181, in iter for obj in iterable: ^^^^^^^^ File "C:\Program Files\Python312\Lib\concurrent\futures_base.py", line 619, in result_iterator yield _result_or_cancel(fs.pop()) ^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "C:\Program Files\Python312\Lib\concurrent\futures_base.py", line 317, in _result_or_cancel return fut.result(timeout) ^^^^^^^^^^^^^^^^^^^ File "C:\Program Files\Python312\Lib\concurrent\futures_base.py", line 456, in result return self.__get_result() ^^^^^^^^^^^^^^^^^^^ File "C:\Program Files\Python312\Lib\concurrent\futures_base.py", line 401, in __get_result raise self._exception File "C:\Program Files\Python312\Lib\concurrent\futures\thread.py", line 59, in run result = self.fn(*self.args, **self.kwargs) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "C:\Users\AliDesktop\AppData\Roaming\Python\Python312\site-packages\huggingface_hub_snapshot_download.py", line 306, in _inner_hf_hub_download return hf_hub_download( ^^^^^^^^^^^^^^^^ File "C:\Users\AliDesktop\AppData\Roaming\Python\Python312\site-packages\huggingface_hub\utils_validators.py", line 114, in _inner_fn return fn(*args, **kwargs) ^^^^^^^^^^^^^^^^^^^ File "C:\Users\AliDesktop\AppData\Roaming\Python\Python312\site-packages\huggingface_hub\file_download.py", line 988, in hf_hub_download return _hf_hub_download_to_local_dir( ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "C:\Users\AliDesktop\AppData\Roaming\Python\Python312\site-packages\huggingface_hub\file_download.py", line 1251, in _hf_hub_download_to_local_dir _raise_on_head_call_error(head_call_error, force_download, local_files_only) File "C:\Users\AliDesktop\AppData\Roaming\Python\Python312\site-packages\huggingface_hub\file_download.py", line 1656, in _raise_on_head_call_error raise head_call_error File "C:\Users\AliDesktop\AppData\Roaming\Python\Python312\site-packages\huggingface_hub\file_download.py", line 1544, in _get_metadata_or_catch_error metadata = get_hf_file_metadata( ^^^^^^^^^^^^^^^^^^^^^ File "C:\Users\AliDesktop\AppData\Roaming\Python\Python312\site-packages\huggingface_hub\utils_validators.py", line 114, in _inner_fn return fn(*args, **kwargs) ^^^^^^^^^^^^^^^^^^^ File "C:\Users\AliDesktop\AppData\Roaming\Python\Python312\site-packages\huggingface_hub\file_download.py", line 1461, in get_hf_file_metadata r = _request_wrapper( ^^^^^^^^^^^^^^^^^ File "C:\Users\AliDesktop\AppData\Roaming\Python\Python312\site-packages\huggingface_hub\file_download.py", line 286, in _request_wrapper response = _request_wrapper( ^^^^^^^^^^^^^^^^^ File "C:\Users\AliDesktop\AppData\Roaming\Python\Python312\site-packages\huggingface_hub\file_download.py", line 310, in _request_wrapper hf_raise_for_status(response) File "C:\Users\AliDesktop\AppData\Roaming\Python\Python312\site-packages\huggingface_hub\utils_http.py", line 426, in hf_raise_for_status raise _format(GatedRepoError, message, response) from e huggingface_hub.errors.GatedRepoError: 403 Client Error. (Request ID: Root=1-6893de32-1ac0caad21d6ad933473f644;89baba6a-e5a1-445e-aa32-1b128838b805)

Cannot access gated repo for url https://huggingface.co/mistralai/Mistral-7B-v0.1/resolve/27d67f1b5f57dc0953326b2601d68371d40ea8da/.gitattributes. Access to model mistralai/Mistral-7B-v0.1 is restricted and you are not in the authorized list. Visit https://huggingface.co/mistralai/Mistral-7B-v0.1 to ask for access.